# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('District', 'District'), ('Gram Panchayat', 'Gram Panchayat')], max_length=10)),
                ('block_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('District Officer', 'District Officer'), ('Gram Panchayat Officer', 'Gram Panchayat Officer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_aadhar', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.TextField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to='api.Profile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
